# Generated by Django 2.2.7 on 2019-12-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approved_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='chat_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_str', models.CharField(blank=True, max_length=1000, null=True)),
                ('room_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='denied_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deny', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='docxFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formName', models.CharField(max_length=30)),
                ('formDocx', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string1', models.CharField(max_length=30)),
                ('string2', models.CharField(max_length=30)),
                ('string3', models.CharField(max_length=30)),
                ('string4', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tag_str',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='DOCXform/')),
                ('tag_document', models.CharField(max_length=30)),
                ('tag_name1', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_target1', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_name2', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_target2', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_name3', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_target3', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_name4', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_target4', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_name5', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_target5', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploaded_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('string_mail', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
